### ISSUE TITLE
Connect to unseen Wi-Fi network[s]

### ISSUE THREAD

**Issue by fvasquez** [helium/gateway-config#66]
Patrons and enterprise users want to save Wi-Fi credentials (SSID and passphrase) onto a Helium Hotspot for connecting later. This simplifies some Helium Hotspot deployments because operators only need to apply power. I'm not convinced such a feature is the best way to address bulk onboarding of Helium Hotspots but that doesn't stop patrons and enterprises from asking for it.

**Comment by shawaj** [comment]
@fvasquez in theory, you should be able to do this from just plugging in the SD card from the Raspberry Pi into another computer and configuring the `wpa_supplicant.conf` file https://www.raspberrypi.org/documentation/configuration/wireless/headless.md

**Comment by fvasquez** [comment]
> @fvasquez in theory, you should be able to do this from just plugging in the SD card from the Raspberry Pi into another computer and configuring the wpa_supplicant.conf file https://www.raspberrypi.org/documentation/configuration/wireless/headless.md

@shawaj Yes, that would probably work. I noticed that balenaCloud gives users the option to specify a WiFi SSID and passphrase when you download balenaOS from the dashboard for a device like the Raspberry Pi 4. I wonder if balenaOS simply generates the `wpa_supplicant.conf` file from a `Dockerfile`.

**Comment by shawaj** [comment]
It's somewhat different on balenaOS as it is based on yocto. It has a system-connections folder in the resin-boot partition which then contains configuration files for WiFi, modems etc.

More info on it here...
https://www.balena.io/docs/reference/OS/network/2.x/

**Comment by shawaj** [comment]
@fvasquez actually also with balenaCloud there is an option to download the config.json and system-connections files without downloading the full OS and you can add these to a "vanilla" balenaOS image.

**Comment by fvasquez** [comment]
> It's somewhat different on balenaOS as it is based on yocto. It has a system-connections folder in the resin-boot partition which then contains configuration files for WiFi, modems etc.

That's cool. ConnMan's support for cellular modems via oFono is hopeless. I had to write my own pppd plugin for ConnMan back when the original Helium Hotspot had cellular built in.

https://github.com/helium/connman/tree/pppd

Congratulations on [HIP19](https://github.com/helium/HIP/pull/92) being approved!

**Comment by shawaj** [comment]
Haha yeah @ryanteck is currently struggling with similar connman stuff - trying to get connman in a container interfacing with network manager / modem manager in the host OS. Quite a pain!
