### ISSUE TITLE
Miner not ready to get p2p status

### ISSUE THREAD

**Issue by ryanteck** [helium/gateway-config#70]
Currently I'm getting the error  <0.526.0>@gateway_config:diagnostics:225 Miner not ready to get p2p status in my logs.

I'm not sure why I'm getting this as from the best I can tell everything is running as it should?

Is there any suggestions on how to resolve this.

Thanks

**Comment by madninja** [comment]
> Currently I'm getting the error <0.526.0>@gateway_config:diagnostics:225 Miner not ready to get p2p status in my logs.
> 
> I'm not sure why I'm getting this as from the best I can tell everything is running as it should?
> 

Presumably you are running miner and the gateway_config service can talk to the miner service over dbus?

**Comment by ryanteck** [comment]
Hmm that seems to be erroring out with 

```Error org.freedesktop.DBus.Error.ServiceUnknown: The name com.helium.Miner was not provided by any .service files```

I believe I've given the miner container access to dbus by running it as:
```docker run -d \
--env REGION_OVERRIDE=EU868 \
--restart always \
--publish 1680:1680/udp \
--publish 44158:44158/tcp \
--name miner \
--privileged \
--env DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket \
--mount type=bind,source=/home/pi/miner_data,target=/var/data \
quay.io/team-helium/miner:latest-arm64```

I also have added the com.helium.Miner.conf file from the miner repository.

I might have missed a step somewhere however?

**Comment by madninja** [comment]
Look in the sys.config for miner. There's a use_ebus variable you need to set to true.. Then rebuild the release and image

**Comment by ryanteck** [comment]
Oh ok so for it to work I need to compile our own docker image rather than use the one that is available?

I'll give that a try. Thanks.

**Comment by madninja** [comment]
Or change the config as part of your docker setup

**Comment by ryanteck** [comment]
Ahh excellent @madninja , that works.

Editing the sys.config file and changing use_ebus to true in the container worked perfect. Know that fixes it now.

Thanks for the help.
