### ISSUE TITLE
Forget WiFi network asks for password again

### ISSUE THREAD

**Issue by shawaj** [helium/gateway-config#72]
When clicking to "forget" a WiFi network in the app, it then takes you to a screen where it asks you to enter the WiFi password for the same network again.

If you click "back" in the app at this point it actually has forgotten the WiFi network and isn't connected.

But if you continue to put the password in it actually reconnects to the same network.

Guess there is a bug somewhere

(Tested using OG and RAK hotspots)

**Comment by cokes518** [comment]
this is filed in the wrong repo, should go to hotspot-app.

Can you confirm the app version and refile? Thanks!

**Comment by shawaj** [comment]
Oops my bad. Will do that now
