### ISSUE TITLE
Install Issues

### ISSUE THREAD

**Issue by darkept** [helium/gateway-config#75]
Hi im new here and i am having this issue right at the start: 

pi@raspberrypi:~ $ git clone https://github.com/helium/gateway-config.git
Cloning into 'gateway-config'...
remote: Enumerating objects: 1224, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 1224 (delta 148), reused 156 (delta 137), pack-reused 1051
Receiving objects: 100% (1224/1224), 1.78 MiB | 3.58 MiB/s, done.
Resolving deltas: 100% (887/887), done.
pi@raspberrypi:~ $ cd gateway-config
pi@raspberrypi:~/gateway-config $ make && make release
./rebar3 compile
/usr/bin/env: ‘escript’: No such file or directory
make: *** [Makefile:16: compile] Error 127

Anyone came across this ?

**Comment by madninja** [comment]
Perhaps you did not install erlang or did not install the right version?

**Comment by darkept** [comment]
thats right! thanks

**Comment by darkept** [comment]
Received this one:

pi@raspberrypi:~ $ git clone https://github.com/helium/gateway-config.git
Cloning into 'gateway-config'...
remote: Enumerating objects: 1224, done.
remote: Counting objects: 100% (173/173), done.
remote: Compressing objects: 100% (36/36), done.
remote: Total 1224 (delta 148), reused 156 (delta 137), pack-reused 1051
Receiving objects: 100% (1224/1224), 1.78 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (887/887), done.
pi@raspberrypi:~ $ cd gateway-config
pi@raspberrypi:~/gateway-config $ make && make release
./rebar3 compile
===> Fetching rebar3_gpb_plugin ({pkg,<<"rebar3_gpb_plugin">>,
                                         <<"2.17.2">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/rebar3_gpb_plugin-2.17.2.tar is up to date, reusing it
===> Fetching gpb ({pkg,<<"gpb">>,<<"4.14.2">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/gpb-4.14.2.tar is up to date, reusing it
===> Compiling gpb
Compiling descriptor.proto...
Compiling gpb_descriptor.erl...
Compiling gpb_compile_descr.proto...
===> Compiling rebar3_gpb_plugin
===> Fetching rebar3_proper ({pkg,<<"rebar3_proper">>,<<"0.12.0">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/rebar3_proper-0.12.0.tar is up to date, reusing it
===> Compiling rebar3_proper
===> Verifying dependencies...
===> Fetching clique ({git,"https://github.com/helium/clique.git",
                                 {ref,
                                     "e4be0dae150061bec080502ed530091672880867"}})
===> Fetching rebar_erl_vsn ({pkg,<<"rebar_erl_vsn">>,<<"0.2.2">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/rebar_erl_vsn-0.2.2.tar is up to date, reusing it
===> Compiling rebar_erl_vsn
===> Fetching connman ({git,"https://github.com/helium/ebus-connman",
                                  {ref,
                                      "0e41b522598bea885a9770fc538ca013c5c384b8"}})
===> Fetching erlang_ale ({git,"https://github.com/helium/erlang_ale",
                                  {ref,
                                   "07e10e656693f07a0d577f3651e76e52680c3768"}})
===> Fetching gatt ({git,"https://github.com/helium/ebus-gatt",
                                {ref,"92732d7d7c153e46f4a7b9bde46c676b8d8476fd"}})
===> Fetching h3 ({git,"https://github.com/helium/erlang-h3.git",
                              {ref,"0bca3fcc9d42fa604637ab561832d962f7572cef"}})
===> Fetching lager ({pkg,<<"lager">>,<<"3.6.7">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/lager-3.6.7.tar is up to date, reusing it
===> Fetching cuttlefish ({git,
                                  "https://github.com/helium/cuttlefish.git",
                                  {ref,
                                   "8672838e8f4ef61602aee6e4ff97ec9be54031dc"}})
===> Fetching ebus ({git,"https://github.com/helium/ebus",
                                {ref,"e49d7845c8c1e19961e529fc8a7fb61eec9973c6"}})
===> Fetching goldrush ({pkg,<<"goldrush">>,<<"0.1.9">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/goldrush-0.1.9.tar is up to date, reusing it
===> Fetching getopt ({pkg,<<"getopt">>,<<"1.0.1">>})
===> Version cached at /home/pi/.cache/rebar3/hex/default/packages/getopt-1.0.1.tar is up to date, reusing it
===> Compiling goldrush
===> Compiling lager
===> Compiling ebus
make[1]: Entering directory '/home/pi/gateway-config/_build/default/lib/ebus/c_src'
cc -g3 -ggdb -std=c99 -finline-functions -Wall -Wmissing-prototypes -I /usr/include/dbus-1.0 -I /usr/lib/dbus-1.0/include -I /usr/lib/aarch64-linux-gnu/dbus-1.0/include -fPIC -I /usr/lib/erlang/erts-10.2.4/include/ -I /usr/lib/erlang/lib/erl_interface-3.10.4/include  -c -o /home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_message.o /home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_message.c
In file included from /home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_message.h:4,
                 from /home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_message.c:1:
/home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_shared.h:4:10: fatal error: dbus/dbus.h: No such file or directory
 #include "dbus/dbus.h"
          ^~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:67: /home/pi/gateway-config/_build/default/lib/ebus/c_src/ebus_message.o] Error 1
make[1]: Leaving directory '/home/pi/gateway-config/_build/default/lib/ebus/c_src'
===> Hook for compile failed!

make: *** [Makefile:16: compile] Error 1


Only thing i am missing is connman as it messes up with my wi-fi. But even with it installed I get the same error

**Comment by madninja** [comment]
From the readme: 

```
To build this project, make sure you have libdbus-1-dev (or its equivalent) and cmake installed on your development machine.
```

**Comment by darkept** [comment]
Tried : 
pi@raspberrypi:~ $ cd gateway-config
pi@raspberrypi:~/gateway-config $ cd _build/prod/rel/gateway_config
pi@raspberrypi:~/gateway-config/_build/prod/rel/gateway_config $ sudo bin/gateway_config start
pi@raspberrypi:~/gateway-config/_build/prod/rel/gateway_config $ 
pi@raspberrypi:~/gateway-config/_build/prod/rel/gateway_config $ 
pi@raspberrypi:~/gateway-config/_build/prod/rel/gateway_config $ sudo bin/gateway_config advertise on
Node 'gateway_config@127.0.0.1' not responding to pings.

**Comment by madninja** [comment]
Did you get this resolved? You'll have to look at the console.log to see what the issue is. Open a new issue if you're still having problems getting this going please?
