### ISSUE TITLE
Documentation on shell usage ./rebar3 shell

### ISSUE THREAD

**Issue by fredsco** [helium/gateway-config#76]
Hi! 

After I run ./rebar3 shell am not sure what commands I can use.. how can I turn on the gateway and turn on bluetooth advertisement? I want to try out the shell and do something similar like this:

`sudo _build/prod/rel/gateway_config/bin/gateway_config start`
`_build/prod/rel/gateway_config/bin/gateway_config advertise on`

**Comment by evanmcc** [comment]
you do those things at the actual shell.  rebar3 shell is a debugging facility that we haven't really set up.
