### ISSUE TITLE
Make Issue in gateway-config

### ISSUE THREAD

**Issue by Hccd2022** [helium/gateway-config#85]
Hi Sir,

While running make under gateway-config, I found ===> Compiling _build/default/plugins/gpb/src/gpb_compile.erl failed. No idea how to solve it. Pls give me some advices.

pi@raspberrypi:~/gateway-config $ make && make release

./rebar3 compile
===> Fetching rebar3_gpb_plugin v2.22.1
===> Fetching gpb v4.19.2
===> Analyzing applications...
===> Compiling gpb

**************************
===> Compiling _build/default/plugins/gpb/src/gpb_compile.erl failed
_build/default/plugins/gpb/src/gpb_compile.erl:105: can't find include lib "**eunit/include/eunit.hrl"; Make sure eunit is in your app file's 'applications' list

===> Errors loading plugin rebar3_gpb_plugin. Run rebar3 with DEBUG=1 set to see errors.
===> Analyzing applications...
===> Compiling gpb
===> Compiling _build/default/plugins/gpb/src/gpb_defs.erl failed
_build/default/plugins/gpb/src/gpb_defs.erl:45: can't find include lib "eunit/include/eunit.hrl"; Make sure eunit is in your app file's 'applications' list

_build/default/plugins/gpb/src/gpb_defs.erl:1675: Warning: function opt_name_4_to_3_test/0 is unused
_build/default/plugins/gpb/src/gpb_defs.erl:1684: Warning: function rpc_opt_name_43_test/0 is unused

===> Errors loading plugin rebar3_gpb_plugin. Run rebar3 with DEBUG=1 set to see errors.
===> Verifying dependencies...
===> Fetching clique (from {git,"https://github.com/helium/clique.git",
                  {ref,"e4be0dae150061bec080502ed530091672880867"}})
===> Fetching rebar_erl_vsn v0.2.2
===> Analyzing applications...
===> Compiling rebar_erl_vsn
===> Compiling _build/default/plugins/gpb/src/gpb_compile.erl failed
_build/default/plugins/gpb/src/gpb_compile.erl:105: can't find include lib "eunit/include/eunit.hrl"; Make sure eunit is in your app file's 'applications' list

===> Errors loading plugin {rebar_erl_vsn,"~>0.2.0"}. Run rebar3 with DEBUG=1 set to see errors.
===> Fetching connman (from {git,"https://github.com/helium/ebus-connman",
                   {ref,"0e41b522598bea885a9770fc538ca013c5c384b8"}})
===> Fetching erlang_ale (from {git,"https://github.com/helium/erlang_ale",
                      {ref,"07e10e656693f07a0d577f3651e76e52680c3768"}})
===> Fetching gatt (from {git,"https://github.com/helium/ebus-gatt",
                {ref,"92732d7d7c153e46f4a7b9bde46c676b8d8476fd"}})
===> Fetching h3 (from {git,"https://github.com/helium/erlang-h3.git",
              {ref,"7ff30d080817f1ed4c170afcfb8825902825b37c"}})
===> Failed to fetch and copy dep: {git,"https://github.com/helium/erlang-h3.git",
                                  {ref,
                                      "7ff30d080817f1ed4c170afcfb8825902825b37c"}}
make: *** [Makefile:16: compile] Error 1

**Comment by madninja** [comment]
How did you install erlang? and what erlang version did you install?

**Comment by Hccd2022** [comment]
I use #sudo apt-get erlang-nox, version is 1.23.2.6

**Comment by madninja** [comment]
That installation looks like it’s missing the eunit package. Check your apt repo for other erlang packages?

**Comment by Hccd2022** [comment]
Yes. I try to install "sudo apt-get install erlang" full version. It is OK now.
But, at the last step, when I input $sudo sv restart dbus
It shows below. 
fail: dbus: unable to change to service directory: file does not exist

**Comment by madninja** [comment]
It looks like you don't have dbus installed?

**Comment by Hccd2022** [comment]
Thanks sir. It is resolved.

**Comment by madninja** [comment]
> Thanks sir. It is resolved.

Would you mind saying how it was resolved so it will be easier to help a future person?

**Comment by Hccd2022** [comment]
Need to install $sudo apt-get install erlang erlang-nox dbus
