### ISSUE TITLE
About gateway-config for Light-Hotspot onboarding

### ISSUE THREAD

**Issue by Visit-Learn** [helium/gateway-config#98]
Hi, I use the latest commit in master branch (SHA-1: 17fefffd41129aee9b053abfb9ab05dec49e361e)
to build the new gateway-config, but some warning as below,
![image](https://user-images.githubusercontent.com/19858499/220623335-cd3bea13-8997-4c9f-bd30-24d441f0f2ae.png)

Do I need some settings to fix this warning?
After that, I used this **gateway-config** and could find BLE advertising.

By the way, one question here, does this latest **gateway-config** is used as a Light-Hotspot 
on boarding flow with BLE by IOS/Android APP?

If yes, which version(tag) of gateway-config you recommended to use?
Thank you so much.

**Comment by fvasquez** [comment]
> By the way, one question here, does this latest gateway-config is used as a Light-Hotspot on boarding flow with BLE by IOS/Android APP?

gateway-config is an Erlang OTP application so it is not meant to be run on Light Hotspots. Light Hotspots are implemented in Rust and do not require an Erlang runtime.

https://github.com/helium/gateway-rs

gateway-config was developed for the original Helium Hotspot which is now discontinued.

**Comment by Visit-Learn** [comment]
> gateway-config is an Erlang OTP application so it is not meant to be run on Light Hotspots. Light Hotspots are implemented in Rust and do not require an Erlang runtime.

Thank you for your response, but I have a little confused here. As I know, the gateway-config is used as BLE and WiFi control which could do the onboarding flow in Full-Helium Hotspot. And now, if there is no gateway-config in Light Helium Hotspot does means that the gateway-rs could control BLE advertsing to do related onboarding flow? Or, the Light Helium Hotspot is not supported by BLE onboarding flow?

Thank you so much.

**Comment by fvasquez** [comment]
> And now, if there is no gateway-config in Light Helium Hotspot does means that the gateway-rs could control BLE advertsing to do related onboarding flow?

The Helium Hotspot App is being deprecated and will be restricted to only managing original Helium Hotspots. Going forward Hotspot management will be handled by individual Maker Apps, so the method of onboarding now depends on each gateway manufacturer. As far as I know, gateway-rs doesn't do onboarding.

You can use the helium_wallet and helium_gateway CLIs to add a Data-Only Hotspot based on gateway-rs to the Helium blockchain.

https://www.disk91.com/2021/technology/lora/helium-data-only-hotspot-with-rak-wisgate-edge-prime/

I don't know what the process is for adding a Light Hotspot.

**Comment by Visit-Learn** [comment]
> > And now, if there is no gateway-config in Light Helium Hotspot does means that the gateway-rs could control BLE advertsing to do related onboarding flow?
> 
> The Helium Hotspot App is being deprecated and will be restricted to only managing original Helium Hotspots. Going forward Hotspot management will be handled by individual Maker Apps, so the method of onboarding now depends on each gateway manufacturer.
> 
> As far as I know, gateway-rs can't do onboarding by itself. However, you can use the helium_wallet CLI in conjunction with the helium_gateway CLI to add a Data-Only Hotspot based on gateway-rs to the Helium blockchain.
> 
> https://www.disk91.com/2021/technology/lora/helium-data-only-hotspot-with-rak-wisgate-edge-prime
> 
> I don't know what the process is for adding a Light Hotspot. It may be different after the upcoming migration to Solana.

Got it, thank you so much.
Now I know the data only onboarding flow could follow above link to do related process. 
And could I think that if I want to know the Light Hotspot further onboarding flow need to waiting it?
And do you know when does Light Hotspot will be ready?

Thank you again.

**Comment by madninja** [comment]
> > > And now, if there is no gateway-config in Light Helium Hotspot does means that the gateway-rs could control BLE advertsing to do related onboarding flow?
> > 
> > 
> > The Helium Hotspot App is being deprecated and will be restricted to only managing original Helium Hotspots. Going forward Hotspot management will be handled by individual Maker Apps, so the method of onboarding now depends on each gateway manufacturer.
> > As far as I know, gateway-rs can't do onboarding by itself. However, you can use the helium_wallet CLI in conjunction with the helium_gateway CLI to add a Data-Only Hotspot based on gateway-rs to the Helium blockchain.
> > https://www.disk91.com/2021/technology/lora/helium-data-only-hotspot-with-rak-wisgate-edge-prime
> > I don't know what the process is for adding a Light Hotspot. It may be different after the upcoming migration to Solana.
> 
> Got it, thank you so much. Now I know the data only onboarding flow could follow above link to do related process. And could I think that if I want to know the Light Hotspot further onboarding flow I need to waiting for it? And do you know when does Light Hotspot will be ready?
> 
> Thank you again.

There are only two kinds of hotspots `full` or `dataonly`. The concept of a "light" hotspot was never used on chain and is only used to indicate that the hotspot no longer includes an Erlang based miner. 

Dataonly a full hotspots are both possible using the [gateway-rs ](https://github.com/helium/gateway-rs) repository though you need to be an approved maker to allow full hotspot onboarding. 

If you want to be a full maker and ship hardware you will need to go through at least HIP 19 approval. which is mostly documented [here](https://docs.helium.com/mine-hnt/full-hotspots)
